### ISSUE TITLE
Travis instructions for "only PRs"

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/appr#1]
As an additional / optional config this section: https://github.com/FormidableLabs/appr#add-travisyml-to-your-project I thought the recommendation for "only PRs + master" was more canonically:

```yml
branches:
  only:
    - master
```
