### ISSUE TITLE
Circle CI 2 doc

### ISSUE THREAD

**Issue by yo7** [FormidableLabs/appr#33]
I’m using `appr` with Circle CI 2.0. If there’s no good reason to document the configuration in CircleCI 1.0 on README, it would be nice to update the doc for developpers like me.

**Comment by jevakallio** [comment]
That's a good idea! We currently have some fundamental questions to answer with appr's future regarding the recent iOS changes in the Expo client (see top of README) but would be nice to have this documented.

If you come up with a setup for your project, I'd love to see a PR!

**Comment by christophehurpeau** [comment]
I can provide an example :

> .circleci/config.yml

```
version: 2

jobs:
  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - dependencies-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn --prefer-offline --pure-lockfile
      - save_cache:
          key: dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint code
          command: yarn run lint
      - run:
          name: Run flow
          command: yarn run flow
      - run:
          name: Run tests
          command: yarn run test

  publish:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Publish
          command: |
            # Needs: EXP_USERNAME, EXP_PASSWORD, GITHUB_USERNAME, GITHUB_TOKEN
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              npx appr
            fi


workflows:
  version: 2

  main-workflow:
    jobs:
      - test
      - publish:
          context: expo
          requires:
            - test
```

You can use [https://circleci.com/docs/2.0/contexts/] and create a expo context with the four env variables: `EXP_USERNAME`, `EXP_PASSWORD`, `GITHUB_USERNAME`, `GITHUB_TOKEN`
